### ISSUE TITLE
Cannot run example in Android Studio 3.4.2

### ISSUE THREAD

**Issue by yaizudamashii** [googlesamples/android-performance#24]
When I click the green triangle button to run "All in benchmark" in GUI, I'm getting 

```
"/Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java" -ea -...
!!! JUnit version 3.8 or later expected:

java.lang.ClassNotFoundException: junit.framework.ComparisonFailure
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.intellij.rt.execution.junit.JUnitStarter.junitVersionChecks(JUnitStarter.java:221)
	at com.intellij.rt.execution.junit.JUnitStarter.canWorkWithJUnitVersion(JUnitStarter.java:207)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:61)

Process finished with exit code 253
```

I tried to Run -> Edit Configurations' Android JUnit to JRE 1.8 (on my Mac) and also to API Level 28.

**Comment by yaizudamashii** [comment]
Ok I had to run tests on an emulator from actual test files.

**Comment by ChrisCraik** [comment]
Sometimes running from the package level will confuse Studio into trying to run on the host instead of the device, which results in that message.

You can try deleting that configuration by clicking the current test dropdown, clicking configurations, and deleting the one that's trying to run on the host, and trying again.
